"use client";
import type { Metadata } from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CatalogoLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <div className="max-w-7xl mx-auto px-4"> 
        {children}
      </div>
    );
  }
  
